### ISSUE TITLE
Problem with defaults are in diferent partitions

### ISSUE THREAD

**Issue by josejuanmontiel** [tryvium-travels/memongo#15]
If i have /home and /tmp in different partitions

[memongo] [INFO]  Starting MongoDB with options &memongo.Options{ShouldUseReplica:false, Port:33655, CachePath:"/home/jose/.cache/memongo", MongoVersion:"4.0.5", DownloadURL:"https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian92-4.0.5.tgz", MongodBin:"", Logger:(*log.Logger)(nil), LogLevel:0, StartupTimeout:10000000000, Auth:false}
[memongo] [INFO]  mongod from https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian92-4.0.5.tgz does not exist in cache, downloading to /home/jose/.cache/memongo/mongodb-linux-x86_64-debian92-4_0_5_tgz_013dacf59f/mongod
2022/05/25 23:16:57 error writing mongod binary from /tmp/795252025 to /home/jose/.cache/memongo/mongodb-linux-x86_64-debian92-4_0_5_tgz_013dacf59f/mongod: rename /tmp/795252025 /home/jose/.cache/memongo/mongodb-linux-x86_64-debian92-4_0_5_tgz_013dacf59f/mongod: invalid cross-device link
Process 9141 has exited with status 1

Seem something [like](https://stackoverflow.com/a/50741908/1713) this works

**Comment by josejuanmontiel** [comment]
Seem that was thinking about... but for some reason didn't work now... 

https://github.com/tryvium-travels/memongo/pull/16

Hope consider this aproach

Thanks

**Comment by saniales** [comment]
I see the path is right, i approved run workflow, please finish your contribution freely mate ;) thank you very much

**Comment by josejuanmontiel** [comment]
Hi @saniales to " finish your contribution freely mate" do I need something more? explaining with more detail de PR #16 ... may i missing something... sorry :)

**Comment by saniales** [comment]
Hey

From your comment i though you did not finish

From my side tests are good, the workflow ran without breaking

I also understand it is complex to add a test case for a case like this one (it's not immediate to simulate multiple partitions on OS level in go tests)

So i guess it LGTM 😊

**Comment by josejuanmontiel** [comment]
ok ... my coment may lead to this conclusion 👍 i'll take the challenge... let me imaging something to night... for the test, if not easy... we can consider merge.

Thanks

**Comment by josejuanmontiel** [comment]
A week (when i said a night i mean a few :D) later... i think #17  it's a better aproach
