### ISSUE TITLE
Could you please add support for centos?

### ISSUE THREAD

**Issue by sbansal7** [tryvium-travels/memongo#2]
Currently, RHEL 7.0 works but RHEL8.0 and centos are not supported. It would be great to add support for them.

**Comment by saniales** [comment]
Hello, 
thanks for your issue.

Indeed support for RHEL 8.0 and centos is not included

Do you have any idea on how we can support this?

**Comment by sbansal7** [comment]
I think it should be as simple as adding a case here: https://github.com/tryvium-travels/memongo/blob/main/mongobin/downloadSpec.go#L208
But GitHub doesn’t have built in runners for RH/centos, and currently I don’t have a way to test it.

**Comment by saniales** [comment]
Please submit a PR with the corrected code, I will take care of the testing okay, including finding a way to run Github Actions with RH8?

``` diff
+ if majorVersion >= 8 {
+     // ...
+ } else if majorVersion >= 7
+     // ...
+ }
``` 

You should also add a test care here
https://github.com/tryvium-travels/memongo/blob/main/mongobin/downloadSpec_test.go#L142

and add a line for "8" and the proper image

after that I will take care of the action part

Thanks again

**Comment by sbansal7** [comment]
Submitted this: https://github.com/tryvium-travels/memongo/pull/3
