### ISSUE TITLE
Issue with Github action

### ISSUE THREAD

**Issue by sushant-ca** [tryvium-travels/memongo#20]
Hi, i have been trying to use this library with github actions and I am getting the following error:
`did not find a mongod binary in the tar from https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2004-6.0.1.tgz`

could this be a version issue or something else?

thanks in advance for the help

**Comment by saniales** [comment]
can you share the actions files part where you use the memongo library to add some context? I will try to help at best as I can

**Comment by sushant-ca** [comment]
hi @saniales ,  i am just running normal tests in my github actions:

```
- name: Test
      run: go test -v ./...
```

also this how i have setup memongo:

```
opts := &memongo.Options{
		MongoVersion:   "6.0.2",
		StartupTimeout: time.Minute,
	}
if runtime.GOARCH == "arm64" {
	if runtime.GOOS == "darwin" {
			// Only set the custom url as workaround for arm64 macs
			opts.DownloadURL = "https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-6.0.2.tgz"
	}
}
mongoServer, err = memongo.StartWithOptions(opts)
```

**Comment by sushant-ca** [comment]
I think there is some issue with mongo v6
works fine with v5.0.13

**Comment by saniales** [comment]
yes, it is definitely a version issue, but we need to dig deeper into this

**Comment by saniales** [comment]
![image](https://user-images.githubusercontent.com/3513298/196755870-ab5d1439-ab9c-4db7-b5c3-6286c3fda24a.png)
Uploading here for reference, the difference between a 5.x tgz and 6.x tgz

> File related may be getOrDownload.go
>
> the absence of `mongo` binary is not the cause of the issue

**Comment by saniales** [comment]
It appears mongoDB from 6 is not available as binary download from mongo website, hence why it is not working, 

A fix is to use custom URL and download from ubuntu 20-04 version (at your risk) or update your vm to use ubuntu 20-04
