### ISSUE TITLE
memongo doesn't properly set permissions for mongod

### ISSUE THREAD

**Issue by mbacchi** [tryvium-travels/memongo#35]
We're using memongo in Go tests. It appears the permissions on the binary in the Mongo `tar.gz` file are set to 644 (or `-rw-r--r--`) and  it fails to execute. I'm not sure if the reason this isn't handled properly is that MongoDB used to distribute the binary with the permissions set to 744 in the past, or if [this section](https://github.com/tryvium-travels/memongo/blob/main/mongobin/getOrDownload.go#L143) of the `_saveFile` function isn't working correctly to run chmod on the file. But the result is that when memongo tries to start it in the cache directory it isn't executable.

I'm running the following command to perform go tests on a Fedora 39 system (RHEL compatible):

`MEMONGO_DOWNLOAD_URL=https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel90-7.0.5.tgz go test -v ./...`

The error I get with debug output is:

```
=== RUN   TestSeedCmdTestSuite
[memongo] [INFO]  Starting MongoDB with options &memongo.Options{ShouldUseReplica:false, Port:37917, CachePath:"/home/testuser/.cache/memongo", MongoVersion:"7.0.5", DownloadURL:"https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel90-7.0.5.tgz", MongodBin:"", Logger:(*log.Logger)(nil), LogLevel:2, StartupTimeout:10000000000, Auth:false}
[memongo] [DEBUG] mongod from https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-rhel90-7.0.5.tgz exists in cache at /home/testuser/.cache/memongo/mongodb-linux-x86_64-rhel90-7_0_5_tgz_57613dff3a/mongod
[memongo] [DEBUG] Using binary /home/testuser/.cache/memongo/mongodb-linux-x86_64-rhel90-7_0_5_tgz_57613dff3a/mongod
[memongo] [DEBUG] Starting mongod
    seed_test.go:30: 
        	Error Trace:	/home/testuser/blah/cmd/seed_test.go:30
        	            	/home/testuser/go/pkg/mod/github.com/stretchr/testify@v1.8.4/suite/suite.go:154
        	            	/home/testuser/blah/cmd/seed_test.go:24
        	Error:      	Received unexpected error:
        	            	fork/exec /home/testuser/.cache/memongo/mongodb-linux-x86_64-rhel90-7_0_5_tgz_57613dff3a/mongod: permission denied
```

And the call to start the memongo server is:

```
mongoServer, err := memongo.StartWithOptions(&memongo.Options{MongoVersion: "7.0.5", LogLevel: memongolog.LogLevel(memongolog.LogLevelDebug)})
```

As a workaround I can manually run `chmod 744` on the cached file after the initial failure. But this seems like it should be handled by memongo to properly set the permissions to executable.

Let me know if there's any more information I can provide.

Thanks,
-Matt

**Comment by saniales** [comment]
A fix is in place, wait for new release.

Remember to clear cache to avoid reuse.

**Comment by saniales** [comment]
A new release has been published @mbacchi. Thank you for your contributions.

https://github.com/tryvium-travels/memongo/releases/tag/v0.12.0

Hope you will book your next travel with us next time. 

https://tryvium.io
