### ISSUE TITLE
afero.Rename errors when copying mongod binary from /tmp mounted on different filesystem

### ISSUE THREAD

**Issue by dgunay** [tryvium-travels/memongo#5]
My system has `/tmp` mounted on a different filesystem, so when `afs.Rename` is called to copy the mongod binary from `/tmp` to the cache, I get the following error:

```
panic: error writing mongod binary from /tmp/192458888 to /home/devin/.cache/memongo/mongodb-linux-x86_64-debian10-4_2_16_tgz_ffac481192/mongod: rename /tmp/192458888 /home/devin/.cache/memongo/mongodb-linux-x86_64-debian10-4_2_16_tgz_ffac481192/mongod: invalid cross-device link
```

This is because it is likely calling `os.Rename`, which cannot move files across filesystems. This can be worked around by [copying the file and then deleting the original if the copy was successful](https://gist.github.com/var23rav/23ae5d0d4d830aff886c3c970b8f6c6b).

**Comment by saniales** [comment]
thanks for the tip, can you make a PR to fix that?

**Comment by dgunay** [comment]
Sure!

**Comment by saniales** [comment]
awesome. Also contact me on telegram @saniales I have something to say to you <3

**Comment by dgunay** [comment]
> awesome. Also contact me on telegram *CENSORED* I have something to say to you <3

I don't use Telegram, unfortunately.

**Comment by saniales** [comment]
drop an email to a.sanino@tryvium.io then :)
